baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Anna Papp'
theme = 'academimal-theme'
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]
googleAnalytics = "G-FPJWJQY0RE"

[params]
    shortbio = "PhD Candidate, Columbia University"
    logo = "anna_papp_website_pic.jpeg" 
