baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Anna Papp'
theme = 'academimal-theme'
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Candidate, SIPA, Columbia University"
    logo = "anna_packraft.jpg" 